# Site settings
title: CGRJ The jam spreading around covent garden
description: "Just a place to bookmark if you like pi."
url: "http://fthdev.github.io"
author:
  name: "Frank TH"
  url: "http://dragonhall.jam@google.co.uk"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.0.1"
